apiVersion: intent.security.nimbus.com/v1alpha1
kind: SecurityIntent
metadata:
  name: e2h
spec:
  intent:
    id: escapeToHost
    description: >-
      A attacker can breach container boundaries and can gain access to the host
      machine
    action: Block
    params:
      psa_level: [baseline]
---
apiVersion: intent.security.nimbus.com/v1alpha1
kind: SecurityIntentBinding
metadata:
  name: nephio-binding-1
  namespace: free5gc-cp
spec:
  intents:
    - name: e2h
  selector:
    workloadSelector:
      matchLabels:
        nf: udr
