apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: free5gc-cp
  labels:
    nf: webui
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "7200"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always

