apiVersion: v1
kind: Pod
metadata:
  name: baseline-pod
  namespace: free5gc-cp
  labels:
    nf: udr
spec:
  containers:
  - name: sec-ctx-4
    image: gcr.io/google-samples/hello-app:2.0
    securityContext:
      capabilities:
        add: ["MKNOD", "CHOWN"]

