apiVersion: v1
kind: Pod
metadata:
  name: restricted-caps-pod
  namespace: free5gc-cp
  labels:
    nf: udr
spec:
  containers:
  - name: sec-ctx-4
    image: gcr.io/google-samples/hello-app:2.0
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add: ["NET_BIND_SERVICE"]
      seccompProfile:
        type: RuntimeDefault

