apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: test
  labels:
    app: atom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atom
  template:
    metadata:
      labels:
        app: atom
    spec:
      containers:
      - name: nginx-pod
        image: nginx
