apiVersion: v1
kind: Pod
metadata:
  name: baseline-caps-pod
  namespace: test
  labels:
    app: atom
spec:
  containers:
  - name: sec-ctx-4
    image: gcr.io/google-samples/hello-app:2.0
    securityContext:
      capabilities:
        add: ["MKNOD", "CHOWN"]

